# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs: 
  one: 
    docker: 
     - image: circleci/node:4.8.2
    steps: 
      - checkout
      - run: echo "Hola"
      - run: mkdir -p my_workspace
      - run: echo "Checking workspace" > my_workspace/echo-output
      - persist_to_workspace: 
              root: my_workspace
              paths:
                  - echo-output
  two: 
    docker:
      - image: circleci/node:4.8.2
      steps: 
        - checkout
        - run: echo "Hello"
        - run: echo "Checking workspace" > my_workspace/echo-output-2

workflows: 
  version: 2.1
  one_and_two:
    jobs:
      - one
      - two
        requires: 
            one


