version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: milelucero98
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            sudo pip install docker-compose
      - run:
          name: Build Docker Image
          command:  docker-compose -f deploy/docker-compose/docker-compose.yml up -d
  test:
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: milelucero98
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
