version: 2.1
  docker:
    - image: circleci/buildpack-deps:stretch
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            sudo pip install docker-compose
      - run:
          name: Build Docker Image
          command:  docker-compose -f deploy/docker-compose/docker-compose.yml up -d
workflows:
  version: 2
  build-master:
    jobs:
      - build

